#ifndef HELPERS_H_INCLUDED
#define HELPERS_H_INCLUDED

#define WINDOW_WIDTH 640
#define WINDOW_HEIGHT 480
#define WINDOW_BPP 32
#define FRAMES_PER_SECOND 30
#define MENU_FRAMES_PER_SECOND 15
#define TILESIZE 32
#define WN 640, 480, 32, SDL_SWSURFACE|SDL_DOUBLEBUF
#define FS 640, 480, 32, SDL_DOUBLEBUF|SDL_FULLSCREEN
#define PI 3.141593
#define CATCHER_RADIUS 45
#define BUTTONSIZE 32

enum State{MAIN_MENU, TITLE, NEW_GAME, CONTINUE, IN_GAME, EDITOR, QUIT, GAME_OVER, SCORESCREEN};

enum Direction{UP, DOWN, LEFT, RIGHT};

struct Coord
{
    int x;
    int y;
};

#endif // HELPERS_H_INCLUDED
